### ISSUE TITLE
timewaste

### ISSUE THREAD

**Issue by codyc4321** [AdeleD/react-paginate#166]
more timewasting software that doesnt run a basic demo

ERROR in ./react_components/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /private/tmp/react-paginate/react_components
 @ ./react_components/index.js 1:288-319

ERROR in ./react_components/PaginationBoxView.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /private/tmp/react-paginate/react_components
 @ ./react_components/PaginationBoxView.js 1:288-319

ERROR in ./react_components/PageView.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /private/tmp/react-paginate/react_components
 @ ./react_components/PageView.js 1:288-319

ERROR in ./react_components/BreakView.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /private/tmp/react-paginate/react_components
 @ ./react_components/BreakView.js 1:288-319

**Comment by codyc4321** [comment]
please do not publish anything that doesn't have a basic demo example working after `npm install; npm start`, thanks

**Comment by doomspork** [comment]
@codyc4321 I _just_ plugged this into a project and worked on the first go.  I'm not the maintainer or a contributor but I would suggest you give it another go and if you're still running into issues rather than attack the _unpaid maintainers_, post the necessary information for someone to help you troubleshoot.

A quick Google search tells me you're likely using a different version of React than this was built for.  Perhaps posting your package.json would be useful?  

Unfortunately I'm only just beginning my React journey so I'm not sure how much help I can be.

**Comment by codyc4321** [comment]
With all due respect, while it's a valid point maintainers of open source repos are "unpaid", that doesn't entitle them to waste other's time. 

when you install 100 open source packages and 95 don't work, there's a pattern, right? I have no intention of using this package, since it doesn't work. I was merely making a point...these young kids should start respecting their elders and the world, and either publish something that _works_ or not publish anything at all

**Comment by codyc4321** [comment]
Please inform me of how many open source repos must be broken for my opinion that young kids should stop publishing things that don't work to be justified

**Comment by codyc4321** [comment]
I've been giving things another go for 3 years now and I've probably wasted 150 hours of my employer's time, costing the world nearly 7500$ and myself immeasurable frustration, and nearly never does one of these useless open repos work. If you disrespect others by wasting their time, eventually somebody is gonna criticize you. I hope you get 1000 more upvotes, it won't change the fact that this javascript community is arrogant and disrespectful by publishing things with broken demos, not posting on their github they're not maintaining it, publishing things that never worked in the first place, etc and so on

**Comment by codyc4321** [comment]
I've given you a thumbs up and a heart in approval, yall sure showed me

**Comment by codyc4321** [comment]
would anybody care to point me to where in this pristine, first-in-class repo it explained which "version of react" it was designed to work with? I'm all ears

**Comment by AdeleD** [comment]
Thank you for calling me a "young kid". The fact is I'm not so young and I also have an employer just like you. I maintain this package during my free time so my goal is to save your time rather than waste it.

If you were not too much annoyed while running "make install" you would have read this little sentence at the end of the execution: 
`npm WARN react-paginate@4.4.4 requires a peer of react@^15.0.0 but none was installed.`

Hope this helps...

**Comment by doomspork** [comment]
@codyc4321 I noticed you haven't contributed any open source packages of any value whatsoever.  Perhaps you could show us all how it's supposed to be done?

Furthermore, I don't think your employers Home Depot or Trilogy Education Services would appreciate you dragging their names through the mud as you make of fool of yourself online throwing a temper tantrum.  Definitely not the qualities you look for in a mentor or educator.

**Comment by Biohazord** [comment]
The sense of entitlement here is staggering. The issue here is with the demo and not the package itself. With the amount of time you took to write this post you could of looked into the issue. Maybe created a pull request or at least let the author know what was up.  

I'm surprised someone who is paid $50 an hour is unable to see that react is a peer dependency. Adding it as a dependency and running install makes it work. Since this is an NPM package that would be installed as a dependency I'm not sure how you would want to handle this scenario.

One thing I will note. the command ```make``` is an assumption about the host system. I'm on windows so I just had to look at the make file. You might want to just list out 

With all that being said. I think this package and all open source software is great. I really enjoy being able to see someone elses take on something I've implemented on my own many times in many different languages.

**Comment by codyc4321** [comment]
I agree, I can apologize for being rude but please consider we're all going through dozens of packages that are publicly published and do not work, on any platform, to boost people's resume, of which I've even heard a friend of mine admit to. I've also one day spent 10 hours downloading and troubleshooting every single publicly published npm package for using Google maps in react, and eventually you just assume when one doesn't work it was due to laziness of something that shouldn't be published being published.

I was wrong to assume that was what happened here. My bad

**Comment by codyc4321** [comment]
I'm sorry but I cannot agree that "all open source software is great", if the demos are going to constantly be broken I feel we're often wasting time trying to see how something works, when it would be faster to write the code ourselves. Therefore, by posting a package publicly online with a broken demo, when someone looks to actually use the package, the end goal, they waste more time trying to find one they can quickly use (by seeing a working demo) then they would be just taking 20 hours to write it themselves.

And it obviously shouldn't take 20 hours to find a package that both works, and has a demo that works. I apologize seriously for the _way_ I said it but I still find it a form of entitlement to have thousands of people publishing code that doesn't work to boost their resume

**Comment by codyc4321** [comment]
@Biohazord I had React installed obviously, this is a react package. What happened was I have tried to use dozens of React packages that claim to have "examples" and using the most recent version of React, none of those "examples" have worked. It is incredibly wasteful of the entire world's time, not just mine, to have to constantly waste hours of your day looking for a package to work, find out none do, and then tell your boss "I know the policy is to build the best thing the fastest but I'm gonna have to build this entire segment myself, none of these packages work."

Now in _this_ case, there's a chance I gave up too soon, but based on past experience with the Javascript (and especially, the React) community, why shouldn't I? npm (and pip) is not a place to stock a resume, yet thousands of people use it to publish broken code. Now maybe you didn't, but you also admitted yourself "The issue here is with the demo and not the package itself. " That was the exact issue I raised Samuel, I had followed the instructions listed on this repo!!! And it didn't work, i.e., timewaste. Timewaste is so common it's gotten incredibly ridiculous, but I will learn from this and retry to get the demo working, and if I was right doing it in the right mindset, I will politely reopen the issue, but I'm going to question (if I was right, it's broken) why the demo isn't removed, as (as you already admitted, the dmeo is broken) it is VERY rude to keep doing this over and over again. Nobody should have to deal with 3-4 hours of waste time per day just trying to find a single thing that works, in this open source "community", if you can even call it that. It should take 10-15 minutes. I recognize 3-4 hours is much less than 20 hours. My point is, there's no reason for a staggering % of these published packages to either:
-not work
-demo not work
-neither package nor demo work

 While it isn't right to act like one myself, which is what I apologized for (I have not apologized for thinking it's rude to published a broken demo, it is, it's just less rude than publishing a broken package), it's beginning to (in general, not blaming you nor adele) look like just open source brats.

**Comment by codyc4321** [comment]
@Biohazord I had (excuse me, but it seems obvious) obviously followed the instructions, including install, and as posted they didn't work on that machine. I think it might have been more obvious if it was worded better. I will now try on this machine.

**Comment by ybur-yug** [comment]
You should take a break and a few deep breaths, @codyc4321. Theres no reason to attack people in a community like this for any reason.
