### ISSUE TITLE
Unable to set tabIndex

### ISSUE THREAD

**Issue by bytor99999** [AdeleD/react-paginate#185]
I have searched everywhere, but even is I pass tabIndex={15000} it doesn't set the tab index. Right now our Search bar/filter and the List cannot be tabbed correctly because it always goes to the pagination buttons. I am not sure what is causing this, I noticed the <a> tags in the codebase set the tabIndex to 0, and not allow us to overwrite that. Does that mean for my components on the screen I need to use negative numbers in order to be tabbed into prior to the last component being the Pagination buttons? Thanks

Mark

**Comment by bfellows37** [comment]
tabindex="0" is hardcoded into the module's code. It is not settable through props

**Comment by Tuapplicacion** [comment]
> tabindex="0" is hardcoded in the module's code. It is not settable through props

Whats the purpose of that attribute? It would be great if it could be used as an page index (then we could apply styles easier only to those li tags without next or prev buttons)

**Comment by bfellows37** [comment]
tabindex sets the order of keyboard-focusable elements. Setting it to a > 0 value will alter the element focusing order in the page. tabindex=0 will register the element as keyboard focusable it normally would based on its location in the DOM.

This implementation is for accessibility, since the anchor elements which have no href attribute are interpreted by screen readers as not focusable. Setting the tabIndex to 0 will explicitly register them to screen readers as interactive elements.

**Comment by bfellows37** [comment]
@bytor99999 if your search bar filter list uses anchors without hrefs or another not-traditionally-interactive element, try setting their tabindex values. That might help

**Comment by bytor99999** [comment]
Thanks for the responses. I think we have a resolution, and many of the places we were using Pagination, we now add infinite scroll. Thanks for all the help.
