### ISSUE TITLE
"Current page" is announced multiple times in the screen reader

### ISSUE THREAD

**Issue by darekkay** [AdeleD/react-paginate#217]
When a page is selected, "current page" is announced 3 times in the screen reader. This comes from `aria-current=page` in `PageView.js`, which is correct. However, it should not be announced multiple times. As NVDA has no major issues with `aria-current`, it might be a (re-)rendering issue in react-paginate, leading to multiple outputs.

I reproduced the problem using the project's demo, Firefox: 60.0.1 and NVDA: 2018.1.

![image](https://user-images.githubusercontent.com/3101914/40852047-7dea7acc-65c9-11e8-8e77-fce1dc50fa28.png)

**Comment by MonsieurV** [comment]
Hi @darekkay,

Thanks for the report @darekkay.

Do we still have this issue with the latest React versions?

React can indeed do multiple renders before we have a stable DOM output (and this depends a lot to how ReactPaginate is integrated). I really don't know how this can interact with screen readers. And I don't see how we can change that from this project: even if we have multiple renders, React gives us at the end only one `aria-current=page` in the DOM; and the screen reader should theoretically takes the last render as reference.

I'll close because I don't think we can fix it, but if someone has more information to tackle it, please re-open.

**Comment by darekkay** [comment]
Hey @MonsieurV ,

I could not reproduce the issue anymore, using the following versions:

- `react-paginate@7.1.3`
- `Firefox@94`
- `NVDA@2021.2`

![image](https://user-images.githubusercontent.com/3101914/140177964-b83b7de2-40d8-43af-a73d-118afb2cf1bc.png)

**Comment by MonsieurV** [comment]
Good news!

This may have been fixed upstream (on React part).

Thanks for the feedback @darekkay.
