### ISSUE TITLE
Issue with checkbox, If we set a checkbox to default UNCHECKED, after we traverse to another page, while returning back, the default unchecked checkbox gets checked automatically 

### ISSUE THREAD

**Issue by superdna12** [AdeleD/react-paginate#407]
Please solve this issue

**Comment by superdna12** [comment]
Initially 
![before](https://user-images.githubusercontent.com/82699446/154049126-9325232c-0de2-4641-bb0f-d473619479ec.png)
After going to another page and then coming back
![after](https://user-images.githubusercontent.com/82699446/154049286-923d5e63-33e4-4a12-b746-8dfd68bb426e.png)

**Comment by MonsieurV** [comment]
You should manage the checkbox state from a parent component, so to keep it when you change pages. (else you certainly have it reset to its default state on page change, because you didn't keep this checkbox state somewhere above)

This is certainly not the library react-paginate changing the checkbox state magically. As there is no code to reproduce and this seems not related, I close.
