### ISSUE TITLE
'Use of eval is strongly discouraged' warning in rollup

### ISSUE THREAD

**Issue by neilgd** [AdeleD/react-paginate#428]
When using rollup to package a component that references react-paginate, it spits out the following warning:

`(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules/react-paginate/dist/react-paginate.js`

I am using version 8.1.3.

Any ideas? Thank you!

**Comment by MonsieurV** [comment]
Hi @neilgd,

This is certainly due to the Babel dist of react-paginate. (Cf [`babel.config.js`](https://github.com/AdeleD/react-paginate/blob/master/babel.config.js)

You can try to transpile yourself from the React-Paginate source code, importing from:

```js
import ReactPaginate from './node_modules/react-paginate/react_components/index.js
```

(Then you are responsible for the right Babel/transpiling settings, if any is required on your target)

**Comment by silverwind** [comment]
The problem comes from `react-hot-loader`. With it removed, there is no more `eval` in the compiled file.

**Comment by MonsieurV** [comment]
I removed it (trying to replace it by react-refresh in dev). No more `eval` in the build indeed. Thanks @silverwind.

@AdeleD can you release https://github.com/AdeleD/react-paginate/releases/tag/v8.1.4? Thx

**Comment by silverwind** [comment]
Another nice thing about this change is that bundle size goes down from 23kB to 15kB.

**Comment by AdeleD** [comment]
Is the replacement of react-hot-loader by react-refresh mandatory? I guess the issue was "just" that react-hot-loader was not correctly removed from the production build, or do I miss something?

**Comment by MonsieurV** [comment]
> Is the replacement of react-hot-loader by react-refresh mandatory? I guess the issue was "just" that react-hot-loader was not correctly removed from the production build, or do I miss something?

Well, I thought the same, then I read the CHANGELOG on 7.1.3 and [related commit](https://github.com/AdeleD/react-paginate/commit/739ebccac9eacc05f29da53db83e0c2b6b103089#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f), then [this comment and quote](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/173#issuecomment-927859914) and finally looked at [this](https://github.com/AdeleD/react-paginate/blob/v8.1.3/babel.config.js#L14) (like @silverwind pointed): the issue is that the Babel config does include the react-hot-loader plugin. And that this config is not really meant to

The Babel plugin for the react-hot-loader is (considered) production safe, and is really minimal. But it does includes an `eval` and some minimal unnecessary code for production. It seems just better for me to do without.

And for the dev experience, react-hot-loader is deprecated, so I tried react-refresh (but my webpack-dev-middleware setup must be wrong atm).

**Comment by AdeleD** [comment]
Ok, I understand. Thanks for the explanation.
