### ISSUE TITLE
provide option for default selection

### ISSUE THREAD

**Issue by knaman2609** [AdeleD/react-paginate#54]
i am using initialSelected for defaultPage selected but it fires a callback thats creating a recursion in the code.How do i set selected page number from outside everytime

**Comment by AdeleD** [comment]
When you instantiate the ReactPaginate component with prop `initialSelected`, the `clickCallback` is called during initialization to allow you to load the appropriate content (depending on the selected page).

Despite this, if you want to set an initial page without calling the `clickCallback`, you can now instantiate the component with prop `forceSelected` instead of `initialSelected`.
