### ISSUE TITLE
Html structure. previous, next links under the subcontainer

### ISSUE THREAD

**Issue by vhpoet** [AdeleD/react-paginate#58]
Is there a good reason not to use widely accepted bootstrap structure having `previous`, `next` in the same level as page numbers? Trying to use bootstrap styling with this is a headache.

```
<ul class="pagination">
  <li class="disabled"><a href="#"><span>«</span></a></li>
  <li class="active"><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">4</a></li>
  <li><a href="#">5</a></li>
  <li><a href="#"><span>»</span></a></li>
</ul>
```

This is the current structure
```
<ul>
  <li class="disabled"><a href="#"><span>«</span></a></li>
  <li>
    <ul>
      <li class="active"><a href="#">1</a></li>
      <li><a href="#">2</a></li>
      <li><a href="#">3</a></li>
      <li><a href="#">4</a></li>
      <li><a href="#">5</a></li>
    </ul>
  </li>
  <li><a href="#"><span>»</span></a></li>
</ul>
```

**Comment by AdeleD** [comment]
Ok, you're right, it would be nice to change that.

There are 2 reasons which are probably bad:

The first one:
* The app for which I've initially made the component used this kind of structure.

The second one:
* I think it would require to move all the content from PaginationListView.js in PaginationBoxView.js because I can't do 
```javascript
return (
	{createFragment(items)}
);
```
in `PaginationListView.js` without any HTML tag around `{createFragment(items)}` if you see what I mean.

But maybe you see another solution? Or maybe it's not so terrible to have all the code into PaginationBoxView.js... ?

**Comment by vhpoet** [comment]
I don't think it's terrible to have them in the same file. I'll work on it if I have time this week.

**Comment by AdeleD** [comment]
Done on release 1.0.0 (I've made a major release to not break the previous version for current users).
Let me know if it works for you. Thanks!

**Comment by vhpoet** [comment]
@AdeleD 

1. Readme is not updated `handlePageClick` / `onPageSelected`
2. Examples are not up to date
3. `onPageSelected` doesn't seem to be working
4. The structure is still a little bit different I think
```
<li>prev</li>
<li><ul>...page...</ul></li>
<li>next</li>
```
instead of 
```
<li>prev</li>
<li>page1</li>
<li>page2</li>
<li>next</li>
```

**Comment by k5o** [comment]
Piggybacking on item 3 of @vhpoet's comment above, `onPageSelected` fails specifically on this line: https://github.com/AdeleD/react-paginate/blob/23e8434255e76146ec430a34957d39bf5e8bc67b/react_components/PaginationBoxView.js#L103

I assume since it's referring to a prop, we should be adding this attribute to our intial `ReactPaginate` component instance?

**Comment by AdeleD** [comment]
Thank you very much for your help.
I've fixed `onPageSelected` on release 1.0.1. It should work now.
Normally there is no more <ul> tag in the structure. Are you sure you see <ul> tags in this version?

**Comment by vhpoet** [comment]
@AdeleD works!! thanks for being so fast :)

P. S. ignore the `ul` thing, I had some weird caching issues.

**Comment by AdeleD** [comment]
Ok cool! :)
Thank you too for pointing out that the usage of the component with Bootstrap was complicated.
